"""initial schema

Revision ID: 48aa1148a0a5
Revises:
Create Date: 2026-02-26 17:41:24.722238

"""
from collections.abc import Sequence

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48aa1148a0a5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("user_email", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=False),
        sa.Column("entity_name", sa.Text(), nullable=True),
        sa.Column(
            "before_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "after_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_entity_id"), "audit_log", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_entity_type"), "audit_log", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False
    )
    op.create_table(
        "autopkg_repo",
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_autopkg_repo")),
        sa.UniqueConstraint("url", name=op.f("uq_autopkg_repo_url")),
    )
    op.create_table(
        "autopkg_run",
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="run_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "trigger_type",
            sa.Enum(
                "scheduled",
                "manual_ui",
                "manual_api",
                "workflow_dispatch",
                name="run_trigger_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("triggered_by", sa.Text(), nullable=True),
        sa.Column("github_run_id", sa.Text(), nullable=True),
        sa.Column("github_run_url", sa.Text(), nullable=True),
        sa.Column(
            "recipe_filter", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("total_recipes", sa.Integer(), nullable=True),
        sa.Column("recipes_succeeded", sa.Integer(), nullable=True),
        sa.Column("recipes_failed", sa.Integer(), nullable=True),
        sa.Column("recipes_imported", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_autopkg_run")),
    )
    op.create_table(
        "catalog",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_production", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog")),
        sa.UniqueConstraint("name", name=op.f("uq_catalog_name")),
    )
    op.create_table(
        "client_machine",
        sa.Column("serial_number", sa.Text(), nullable=False),
        sa.Column("hostname", sa.Text(), nullable=True),
        sa.Column("os_version", sa.Text(), nullable=True),
        sa.Column("os_build", sa.Text(), nullable=True),
        sa.Column("machine_model", sa.Text(), nullable=True),
        sa.Column("cpu_type", sa.Text(), nullable=True),
        sa.Column("ram_mb", sa.Integer(), nullable=True),
        sa.Column("disk_size_gb", sa.Integer(), nullable=True),
        sa.Column("disk_free_gb", sa.Integer(), nullable=True),
        sa.Column("munki_version", sa.Text(), nullable=True),
        sa.Column("manifest_name", sa.Text(), nullable=True),
        sa.Column("client_identifier", sa.Text(), nullable=True),
        sa.Column(
            "hardware_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "installed_software", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("last_checkin_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_checkin_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_machine")),
        sa.UniqueConstraint(
            "serial_number", name=op.f("uq_client_machine_serial_number")
        ),
    )
    op.create_index(
        op.f("ix_client_machine_hostname"), "client_machine", ["hostname"], unique=False
    )
    op.create_index(
        op.f("ix_client_machine_last_checkin_at"),
        "client_machine",
        ["last_checkin_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_machine_manifest_name"),
        "client_machine",
        ["manifest_name"],
        unique=False,
    )
    op.create_table(
        "icon",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("s3_path", sa.Text(), nullable=True),
        sa.Column("content_type", sa.Text(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_icon")),
        sa.UniqueConstraint("name", name=op.f("uq_icon_name")),
    )
    op.create_table(
        "manifest",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column(
            "conditional_items", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manifest")),
        sa.UniqueConstraint("name", name=op.f("uq_manifest_name")),
    )
    op.create_table(
        "pkg_info",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("developer", sa.Text(), nullable=True),
        sa.Column("icon_name", sa.Text(), nullable=True),
        sa.Column("installer_item_location", sa.Text(), nullable=True),
        sa.Column("installer_item_hash", sa.Text(), nullable=True),
        sa.Column("installer_item_size", sa.Integer(), nullable=True),
        sa.Column("installed_size", sa.Integer(), nullable=True),
        sa.Column("installer_type", sa.Text(), nullable=True),
        sa.Column("minimum_os_version", sa.Text(), nullable=True),
        sa.Column("maximum_os_version", sa.Text(), nullable=True),
        sa.Column("uninstall_method", sa.Text(), nullable=True),
        sa.Column("unattended_install", sa.Boolean(), nullable=False),
        sa.Column("unattended_uninstall", sa.Boolean(), nullable=False),
        sa.Column("autoremove", sa.Boolean(), nullable=False),
        sa.Column("uninstallable", sa.Boolean(), nullable=False),
        sa.Column("installs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("receipts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "blocking_applications",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "items_to_copy", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "supported_architectures",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("requires", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("update_for", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("preinstall_script", sa.Text(), nullable=True),
        sa.Column("postinstall_script", sa.Text(), nullable=True),
        sa.Column("preuninstall_script", sa.Text(), nullable=True),
        sa.Column("postuninstall_script", sa.Text(), nullable=True),
        sa.Column("installcheck_script", sa.Text(), nullable=True),
        sa.Column("uninstallcheck_script", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_plist", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pkg_info")),
        sa.UniqueConstraint("name", "version", name="uq_pkg_info_name_version"),
    )
    op.create_index(
        op.f("ix_pkg_info_category"), "pkg_info", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_pkg_info_is_deleted"), "pkg_info", ["is_deleted"], unique=False
    )
    op.create_index(op.f("ix_pkg_info_name"), "pkg_info", ["name"], unique=False)
    op.create_table(
        "sync_job",
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "completed", "failed", name="sync_status_enum"
            ),
            nullable=False,
        ),
        sa.Column("triggered_by", sa.Text(), nullable=True),
        sa.Column("trigger_type", sa.Text(), nullable=True),
        sa.Column("github_run_id", sa.Text(), nullable=True),
        sa.Column("files_synced", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_job")),
    )
    op.create_table(
        "user",
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("admin", "editor", "viewer", name="user_role_enum"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "autopkg_recipe",
        sa.Column("identifier", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("parent_recipe", sa.Text(), nullable=True),
        sa.Column("repo_id", sa.UUID(), nullable=True),
        sa.Column(
            "override_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("trust_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "input_variables", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_override", sa.Boolean(), nullable=False),
        sa.Column("auto_promote", sa.Boolean(), nullable=False),
        sa.Column(
            "target_catalogs", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_status", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["autopkg_repo.id"],
            name=op.f("fk_autopkg_recipe_repo_id_autopkg_repo"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_autopkg_recipe")),
        sa.UniqueConstraint("identifier", name=op.f("uq_autopkg_recipe_identifier")),
    )
    op.create_index(
        op.f("ix_autopkg_recipe_name"), "autopkg_recipe", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_autopkg_recipe_repo_id"), "autopkg_recipe", ["repo_id"], unique=False
    )
    op.create_table(
        "autopkg_run_result",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("recipe_identifier", sa.Text(), nullable=False),
        sa.Column("recipe_name", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "success",
                "imported",
                "no_change",
                "failed",
                "trust_failed",
                name="recipe_result_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("imported_version", sa.Text(), nullable=True),
        sa.Column("imported_pkg_path", sa.Text(), nullable=True),
        sa.Column("imported_pkginfo_path", sa.Text(), nullable=True),
        sa.Column(
            "imported_catalogs", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "virustotal_results", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "trust_info_diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "approval_status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "auto_approved",
                name="approval_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("approved_by", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_comment", sa.Text(), nullable=True),
        sa.Column("log_output", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["autopkg_run.id"],
            name=op.f("fk_autopkg_run_result_run_id_autopkg_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_autopkg_run_result")),
    )
    op.create_index(
        op.f("ix_autopkg_run_result_run_id"),
        "autopkg_run_result",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "client_install_report",
        sa.Column("machine_id", sa.UUID(), nullable=False),
        sa.Column("item_name", sa.Text(), nullable=False),
        sa.Column("item_version", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("install_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["client_machine.id"],
            name=op.f("fk_client_install_report_machine_id_client_machine"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_install_report")),
    )
    op.create_index(
        op.f("ix_client_install_report_item_name"),
        "client_install_report",
        ["item_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_install_report_machine_id"),
        "client_install_report",
        ["machine_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_install_report_status"),
        "client_install_report",
        ["status"],
        unique=False,
    )
    op.create_table(
        "manifest_catalog",
        sa.Column("manifest_id", sa.UUID(), nullable=False),
        sa.Column("catalog_id", sa.UUID(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_id"],
            ["catalog.id"],
            name=op.f("fk_manifest_catalog_catalog_id_catalog"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["manifest_id"],
            ["manifest.id"],
            name=op.f("fk_manifest_catalog_manifest_id_manifest"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "manifest_id", "catalog_id", name=op.f("pk_manifest_catalog")
        ),
    )
    op.create_table(
        "manifest_inclusion",
        sa.Column("parent_manifest_id", sa.UUID(), nullable=False),
        sa.Column("child_manifest_id", sa.UUID(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_manifest_id"],
            ["manifest.id"],
            name=op.f("fk_manifest_inclusion_child_manifest_id_manifest"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_manifest_id"],
            ["manifest.id"],
            name=op.f("fk_manifest_inclusion_parent_manifest_id_manifest"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "parent_manifest_id",
            "child_manifest_id",
            name=op.f("pk_manifest_inclusion"),
        ),
    )
    op.create_table(
        "manifest_item",
        sa.Column("manifest_id", sa.UUID(), nullable=False),
        sa.Column("item_name", sa.Text(), nullable=False),
        sa.Column(
            "item_type",
            sa.Enum(
                "managed_installs",
                "managed_uninstalls",
                "managed_updates",
                "optional_installs",
                "featured_items",
                "default_installs",
                name="item_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["manifest_id"],
            ["manifest.id"],
            name=op.f("fk_manifest_item_manifest_id_manifest"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manifest_item")),
    )
    op.create_index(
        op.f("ix_manifest_item_manifest_id"),
        "manifest_item",
        ["manifest_id"],
        unique=False,
    )
    op.create_table(
        "pkg_info_catalog",
        sa.Column("pkg_info_id", sa.UUID(), nullable=False),
        sa.Column("catalog_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_id"],
            ["catalog.id"],
            name=op.f("fk_pkg_info_catalog_catalog_id_catalog"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pkg_info_id"],
            ["pkg_info.id"],
            name=op.f("fk_pkg_info_catalog_pkg_info_id_pkg_info"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "pkg_info_id", "catalog_id", name=op.f("pk_pkg_info_catalog")
        ),
    )
    op.create_table(
        "promotion_rule",
        sa.Column("pkginfo_name", sa.Text(), nullable=False),
        sa.Column("source_catalog_id", sa.UUID(), nullable=False),
        sa.Column("target_catalog_id", sa.UUID(), nullable=False),
        sa.Column(
            "strategy",
            sa.Enum(
                "manual",
                "auto_time",
                "auto_approve",
                "auto_immediate",
                name="promotion_strategy_enum",
            ),
            nullable=False,
        ),
        sa.Column("auto_promote_days", sa.Integer(), nullable=True),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["source_catalog_id"],
            ["catalog.id"],
            name=op.f("fk_promotion_rule_source_catalog_id_catalog"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_catalog_id"],
            ["catalog.id"],
            name=op.f("fk_promotion_rule_target_catalog_id_catalog"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promotion_rule")),
    )
    op.create_index(
        op.f("ix_promotion_rule_pkginfo_name"),
        "promotion_rule",
        ["pkginfo_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_promotion_rule_pkginfo_name"), table_name="promotion_rule")
    op.drop_table("promotion_rule")
    op.drop_table("pkg_info_catalog")
    op.drop_index(op.f("ix_manifest_item_manifest_id"), table_name="manifest_item")
    op.drop_table("manifest_item")
    op.drop_table("manifest_inclusion")
    op.drop_table("manifest_catalog")
    op.drop_index(
        op.f("ix_client_install_report_status"), table_name="client_install_report"
    )
    op.drop_index(
        op.f("ix_client_install_report_machine_id"), table_name="client_install_report"
    )
    op.drop_index(
        op.f("ix_client_install_report_item_name"), table_name="client_install_report"
    )
    op.drop_table("client_install_report")
    op.drop_index(op.f("ix_autopkg_run_result_run_id"), table_name="autopkg_run_result")
    op.drop_table("autopkg_run_result")
    op.drop_index(op.f("ix_autopkg_recipe_repo_id"), table_name="autopkg_recipe")
    op.drop_index(op.f("ix_autopkg_recipe_name"), table_name="autopkg_recipe")
    op.drop_table("autopkg_recipe")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("sync_job")
    op.drop_index(op.f("ix_pkg_info_name"), table_name="pkg_info")
    op.drop_index(op.f("ix_pkg_info_is_deleted"), table_name="pkg_info")
    op.drop_index(op.f("ix_pkg_info_category"), table_name="pkg_info")
    op.drop_table("pkg_info")
    op.drop_table("manifest")
    op.drop_table("icon")
    op.drop_index(op.f("ix_client_machine_manifest_name"), table_name="client_machine")
    op.drop_index(
        op.f("ix_client_machine_last_checkin_at"), table_name="client_machine"
    )
    op.drop_index(op.f("ix_client_machine_hostname"), table_name="client_machine")
    op.drop_table("client_machine")
    op.drop_table("catalog")
    op.drop_table("autopkg_run")
    op.drop_table("autopkg_repo")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_entity_type"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_entity_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
