"""add github recipe cache tables

Revision ID: 5456dfc48cd0
Revises: 48aa1148a0a5
Create Date: 2026-02-27 12:21:49.584032

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5456dfc48cd0"
down_revision: str | None = "48aa1148a0a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_recipe_repo",
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("html_url", sa.Text(), nullable=False),
        sa.Column("clone_url", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=True),
        sa.Column(
            "synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_github_recipe_repo")),
    )
    op.create_index(
        op.f("ix_github_recipe_repo_full_name"),
        "github_recipe_repo",
        ["full_name"],
        unique=True,
    )
    op.create_index(
        op.f("ix_github_recipe_repo_name"), "github_recipe_repo", ["name"], unique=False
    )
    op.create_table(
        "github_recipe",
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("identifier_guess", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["github_recipe_repo.id"],
            name=op.f("fk_github_recipe_repo_id_github_recipe_repo"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_github_recipe")),
    )
    op.create_index(
        op.f("ix_github_recipe_identifier_guess"),
        "github_recipe",
        ["identifier_guess"],
        unique=False,
    )
    op.create_index(
        op.f("ix_github_recipe_name"), "github_recipe", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_github_recipe_repo_id"), "github_recipe", ["repo_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_github_recipe_repo_id"), table_name="github_recipe")
    op.drop_index(op.f("ix_github_recipe_name"), table_name="github_recipe")
    op.drop_index(op.f("ix_github_recipe_identifier_guess"), table_name="github_recipe")
    op.drop_table("github_recipe")
    op.drop_index(op.f("ix_github_recipe_repo_name"), table_name="github_recipe_repo")
    op.drop_index(
        op.f("ix_github_recipe_repo_full_name"), table_name="github_recipe_repo"
    )
    op.drop_table("github_recipe_repo")
    # ### end Alembic commands ###
