name: AutoMerge

on:
  push:
    branches:
      - "autopkg-**"
      - "autopromote-**"

jobs:
  merge-branch:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MunkiRepo (this repo)
        uses: actions/checkout@v3
      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@ab95ff5efbc98a970305f21549646164fc7c0556
        if: always()
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          enforce_admins: false
      - name: Get Branch Name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Merge the AutoPkg Branch
        uses: everlytic/branch-merge@c4a244dc23143f824ae6c022a10732566cb8e973 # v1.1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_ref: ${{ github.ref }}
          target_branch: "main"
          commit_message_template: "feat: Merged ${{ env.BRANCH_NAME }}"

      - name: Delete Branch
        run: |
          git push origin --delete ${{ github.ref }}
      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@ab95ff5efbc98a970305f21549646164fc7c0556
        if: always() # Force to always run this step to ensure "include administrators" is always turned back on
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          enforce_admins: true
